### ISSUE TITLE
Configure Github Repository

### ISSUE THREAD

**Issue by WillTrem** [WillTrem/COMP345_Warzone#6]
### Tasks 
- [ ] Create a milestone for each iteration
- [ ] Establish rules for PR review/approval before merging to main branch
- [ ] Invite every member as a collaborator
- [ ] Add IP opt-out document 
- [ ] Create 'CourseAdmin' folder
